version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/stelligent/config-lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}'
      - run:
          name: Dependencies
            command: GO111MODULE=on go mod download
      - run: 
          name: Test
          command: make test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"
      - persist_to_workspace:
          root: .
          paths: .
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/stelligent/config-lint
    steps:
      - attach_workspace:
          at: /go/src/github.com/stelligent/config-lint
      - run:
          name: Release
          command: |
            go get github.com/goreleaser/goreleaser
            goreleaser release --skip-validate

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
