version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/stelligent/config-lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-cache
      - run: 
          name: Dependencies
          command: make deps
      - run: 
          name: Test
          command: make test
      - save_cache:
          key: go-pkg-cache
          paths:
            - "/go/pkg"
      - persist_to_workspace:
          root: .
          paths: .
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/stelligent/config-lint
    steps:
      - attach_workspace:
          at: /go/src/github.com/stelligent/config-lint
      - run:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/