version: 1
description: Rules for AWS Config
type: AWSConfig
rules:

  - id: DYNAMODB_THROUGHPUT
    message: Table status must have provisionedThroughput
    resource: AWS::DynamoDB::Table
    assertions:
      - key: provisionedThroughput.writeCapacityUnits
        op: present
      - key: provisionedThroughput.readCapacityUnits
        op: present
    severity: NON_COMPLIANT

  - id: SSH_ACCESS
    message: Security group should not allow ingress from 0.0.0.0/0
    resource: AWS::EC2::SecurityGroup
    except:
      - sg-88206cff
      - sg-da652daf
    assertions:
      - none:
         key: "ipPermissions[]"
         assertions:
           - key: fromPort
             op: eq
             value: 22
             value_type: integer
           - key: "ipRanges[]"
             op: contains
             value: 0.0.0.0/0
    severity: NON_COMPLIANT
