Version: 1
Description: Rules for AWS Config
Type: AWSConfig
Rules:
  - id: CFG1
    message: Table status must have provisionedThroughput
    resource: AWS::DynamoDB::Table
    assertions:
      - type: value
        key: provisionedThroughput.writeCapacityUnits
        op: present
    severity: NON_COMPLIANT
  - id: CFG2
    message: Table status must have provisionedThroughput
    resource: AWS::DynamoDB::Table
    assertions:
      - type: value
        key: provisionedThroughput.readCapacityUnits
        op: present
    severity: NON_COMPLIANT
  - id: SG1
    message: Security group should not allow ingress from 0.0.0.0/0
    resource: AWS::EC2::SecurityGroup
    except:
      - sg-88206cff
    assertions:
      - not:
          - and:
              - type: value
                key: ipPermissions[].fromPort[]
                op: contains
                value: "22"
              - type: value
                key: ipPermissions[].ipRanges[]
                op: contains
                value: 0.0.0.0/0
    severity: NON_COMPLIANT
