
name: GHPagesDoc

on:
  push:
    branches:
      - feature/github_pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: deploy ghpages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs